CANONICAL_GENRE_MAP = {
    "hip hop": "hip hop",
    "rap": "hip hop",
    "trap": "hip hop",
    "boom bap": "hip hop",
    "west coast hip hop": "hip hop",
    "emo rap": "hip hop",
    "melodic rap": "hip hop",

    "pop": "pop",
    "synthpop": "pop",
    "bedroom pop": "pop",
    "soft pop": "pop",
    "electropop": "pop",
    "art pop": "pop",
    "indie pop": "pop",

    "rock": "rock",
    "punk": "rock",
    "emo": "rock",
    "emo pop": "rock",
    "pop punk": "rock",
    "skate punk": "rock",
    "post-grunge": "rock",
    "grunge": "rock",
    "classic rock": "rock",
    "hard rock": "rock",
    "alternative rock": "rock",
    "indie rock": "rock",
    "garage rock": "rock",
    "folk rock": "rock",
    "modern rock": "rock",
    "glam rock": "rock",
    "stoner rock": "rock",
    "southern rock": "rock",
    "psychedelic rock": "rock",
    "funk rock": "rock",
    "rap rock": "rock",

    "metal": "metal",
    "nu metal": "metal",
    "doom metal": "metal",
    "gothic metal": "metal",
    "folk metal": "metal",
    "power metal": "metal",
    "symphonic metal": "metal",

    "r&b": "r&b",
    "neo soul": "r&b",
    "motown": "r&b",
    "quiet storm": "r&b",
    "soul": "r&b",
    "indie r&b": "r&b",
    "alternative r&b": "r&b",

    "electronic": "electronic",
    "edm": "electronic",
    "electro": "electronic",
    "house": "electronic",
    "progressive house": "electronic",
    "tropical house": "electronic",
    "dubstep": "electronic",
    "trip hop": "electronic",
    "chillstep": "electronic",
    "future bass": "electronic",
    "glitch": "electronic",
    "nu jazz": "electronic",
    "downtempo": "electronic",
    "drum and bass": "electronic",
    "idm": "electronic",

    "folk": "folk",
    "indie folk": "folk",
    "americana": "folk",
    "alt country": "folk",
    "bluegrass": "folk",
    "singer-songwriter": "folk",

    "country": "country",
    "pop country": "country",
    "traditional country": "country",
    "honky tonk": "country",
    "texas country": "country",
    "country rock": "country",
    "acoustic country": "country",

    "k-pop": "k-pop",
    "k-rap": "k-pop",
    "k-rock": "k-pop",
    "k-ballad": "k-pop",

    "reggae": "reggae",
    "roots reggae": "reggae",
    "reggaeton": "reggae",
    "ska": "reggae",

    "jazz": "jazz",
    "jazz rap": "jazz",
    "acid jazz": "jazz",

    "classical": "classical",
    "musicals": "classical",
    "chamber pop": "classical",
    "baroque pop": "classical",

    "christian": "christian",
    "worship": "christian",
    "ccm": "christian",
    "christian pop": "christian",

    "other": "other"
}
